### ISSUE TITLE
Swimmer mujoco settings

### ISSUE THREAD

**Issue by sytham** [openai/rllab#124]
Hi, do you happen to know why the swimmer settings for the integrator and constraint solver are as they are? In particular, many integrator iterations (frameskip=50) with a tiny timestep (0.001), and many constraint solver iterations (1000) with no warmstart. This makes the simulation quite slow, especially when collisions are involved. For example, the swimmer in OpenAI Gym uses an RK4 integrator with timestep=0.01 and frameskip=4, which is a lot faster. Other rllab models also do not seem to use such extreme settings.

**Comment by dementrock** [comment]
Hi,

I think in general the environments in OpenAI Gym are better tuned. We did not update the existing environments in rllab much since it might change the behavior and the results in our paper would not be reproducible anymore. However you are welcome to make pull requests for alternative versions of the environments (as long as the current ones are still accessible).

**Comment by sytham** [comment]
Okay thanks, I'll fiddle with it -- in particular to see what happens if I use the Gym settings.
