### ISSUE TITLE
Question about orientation in gather_env

### ISSUE THREAD

**Issue by lchenat** [openai/rllab#52]
I am a bit confused about how the orientation is calculated in gather_env.py

On line 289 of gather_env.py:

ori = self.inner_env.model.data.qpos[self.**class**.ORI_IND]

For example, Ant class has ORI_IND 6, and in ant.xml the first joint is the free 'root' joint, then ori should be the value on k axis, since for free joint qpos should be: (x,y,z,a,i,j,k). But ori seems to be the orientation of the agent from the code. Do I misunderstand something?

**Comment by dementrock** [comment]
Hmm I think you are right, and the orientation was not computed correctly. I'm really sorry about this. Would you like to submit a pull request with the corrected orientation?

We have not been doing much experiments with the Ant, since the SwimmerGather was already pretty challenging (I believe the orientation should be correct there). But it will be important to correct this.
