### ISSUE TITLE
Recording GymEnv force_reset=False

### ISSUE THREAD

**Issue by leduckhc** [openai/rllab#70]
Hi I am not sure whether comments in new commit works. So I rather rephrase my question here,

Running experiments for GymEnv did not work for me after updating to the current version. Especially,
what is a purpose of `force_reset=False`? I have running in `stub`bed mode with `run_experiment_lite` (two processes `n_parallel=2`). Usually after two iterations the problem occurs and training is blocked. I figured out that video recording is somehow blocking the threads/processes while in `parallel_sampler.sample_paths(..)` After changing `force_reset` to `True` the issue is solved.

**Comment by dementrock** [comment]
Gym environments throw an error when the environment is reset before the time limit is reached, and force_reset circumvents this limit. In parallel mode, when training is blocked this is likely because some error occurred which has been consumed by the subprocesses (in principle we could have done error handling better). To quickly find the error you could place a try/catch block in the rollout function (https://github.com/openai/rllab/blob/master/rllab/sampler/utils.py)

**Comment by leduckhc** [comment]
That sounds plausible, thank you.
